#!/bin/bash

FROM_REPO=https://github.com/rancher/charts
FROM_BRANCH=release-v2.5

TO_REPO=https://github.com/rancher/charts
TO_BRANCH=dev-v2.5-source

# Additional context to standardize dirs
FROM_TYPE=live
TO_TYPE=source
# MIGRATE=1