#!/bin/bash

cd $(dirname $0)
source ./config

cd ..

rm -rf ${FROM_BRANCH}
rm -rf ${TO_BRANCH}
rm -rf diff
rm -rf $(basename ${FROM_REPO})
rm -rf $(basename ${TO_REPO})

mkdir -p ${FROM_BRANCH}/charts
mkdir -p ${TO_BRANCH}/charts

REPO_DIR=$(basename ${FROM_REPO})
git clone --depth 1 --branch ${FROM_BRANCH} ${FROM_REPO} 2>/dev/null
pushd ${REPO_DIR}
make charts
popd
mv ${REPO_DIR}/charts/* ${FROM_BRANCH}/charts
rm -rf ${REPO_DIR}

REPO_DIR=$(basename ${TO_REPO})
git clone --depth 1 --branch ${TO_BRANCH} ${TO_REPO} 2>/dev/null
pushd ${REPO_DIR}
make charts
popd
mv ${REPO_DIR}/charts/* ${TO_BRANCH}/charts
rm -rf ${REPO_DIR}